### ISSUE TITLE
As a JendaMark Admin I would like to manage all common asset/tool data from a single source i.e. Odin Platform so that data is not duplicated across all applications

### ISSUE THREAD

**Issue by MMDRT-ver3** [MMDRT-ver3/trial_ver1#3]
##### -**Functional Context :**
    Common data exists across all applications. Idea is to bring this redundant data in one manageable asset and 
    use aliasing to have it specified per application

##### -**Technical Context :**
     **In SSO :**
    Create master versions of the tables from the targeted application (Service/Tool Change) along with common fields
    Create CRUD endpoints for APIs of new tables
    Identify new API endpoints required for Integration with targeted applications 

### **Acceptance Criteria**
*  Master Data is managed from at Odin Platform 
   * Create a master data (eg:-asset)
   * Edit
   * Delete

### **Sub-Tasks**
- [ ] Create Table Master Asset
- [ ] Create CRUD endpoints for Master Asset Table API 
- [ ] RnD : Identify new Endpoints
- [ ] Screen for Asset Management in Odin Platform
- [ ] CRUD operation in UI of Odin Platform (Integration)
- [ ] Allow for only JM Admin  and Client Admin

### **Attachments**

- [MDM - Master Data Management](https://docs.google.com/document/d/1Gy-QcdUEAE61fywGUqDff1qrwtdwSGX4ZxlJqfqhDcM/edit?ts=5fdf9028)
